{num_events: 9, num_supervisors: 1, events: [EV_full_rotate, EV_move_forward, EV_obstacle_front,
    EV_obstacle_left, EV_obstacle_right, EV_path_clear, EV_random_walk, EV_rotate_clockwise,
    EV_rotate_counterclockwise], ev_controllable: [1, 1, 0, 0, 0, 0, 1, 1, 1], sup_events: [
    [1, 1, 1, 1, 1, 1, 1, 1, 1]], sup_init_state: [3], sup_current_state: [3], sup_data_pos: [
    0], sup_data: [5, EV_obstacle_front, 0, 11, EV_obstacle_left, 0, 27, EV_obstacle_right,
    0, 43, EV_path_clear, 0, 0, EV_random_walk, 0, 6, 5, EV_obstacle_front, 0, 11,
    EV_obstacle_left, 0, 27, EV_obstacle_right, 0, 43, EV_path_clear, 0, 0, EV_random_walk,
    0, 6, 5, EV_obstacle_front, 0, 14, EV_obstacle_left, 0, 30, EV_obstacle_right,
    0, 46, EV_path_clear, 0, 2, EV_random_walk, 0, 6, 5, EV_obstacle_front, 0, 16,
    EV_obstacle_left, 0, 32, EV_obstacle_right, 0, 48, EV_path_clear, 0, 3, EV_random_walk,
    0, 6, 5, EV_obstacle_front, 0, 19, EV_obstacle_left, 0, 35, EV_obstacle_right,
    0, 51, EV_path_clear, 0, 4, EV_random_walk, 0, 6, 5, EV_obstacle_front, 0, 19,
    EV_obstacle_left, 0, 35, EV_obstacle_right, 0, 51, EV_path_clear, 0, 4, EV_random_walk,
    0, 6, 5, EV_move_forward, 0, 1, EV_obstacle_front, 0, 19, EV_obstacle_left, 0,
    35, EV_obstacle_right, 0, 51, EV_path_clear, 0, 5, 5, EV_obstacle_front, 0, 21,
    EV_obstacle_left, 0, 38, EV_obstacle_right, 0, 53, EV_path_clear, 0, 7, EV_random_walk,
    0, 6, 5, EV_obstacle_front, 0, 24, EV_obstacle_left, 0, 40, EV_obstacle_right,
    0, 56, EV_path_clear, 0, 8, EV_random_walk, 0, 6, 5, EV_obstacle_front, 0, 11,
    EV_obstacle_left, 0, 27, EV_obstacle_right, 0, 43, EV_path_clear, 0, 0, EV_random_walk,
    0, 17, 5, EV_full_rotate, 0, 12, EV_obstacle_front, 0, 10, EV_obstacle_left, 0,
    26, EV_obstacle_right, 0, 42, EV_path_clear, 0, 0, 5, EV_obstacle_front, 0, 10,
    EV_obstacle_left, 0, 26, EV_obstacle_right, 0, 43, EV_path_clear, 0, 0, EV_rotate_clockwise,
    0, 22, 5, EV_obstacle_front, 0, 14, EV_obstacle_left, 0, 30, EV_obstacle_right,
    0, 46, EV_path_clear, 0, 2, EV_random_walk, 0, 17, 5, EV_full_rotate, 0, 12, EV_obstacle_front,
    0, 13, EV_obstacle_left, 0, 29, EV_obstacle_right, 0, 45, EV_path_clear, 0, 2,
    5, EV_obstacle_front, 0, 13, EV_obstacle_left, 0, 29, EV_obstacle_right, 0, 46,
    EV_path_clear, 0, 2, EV_rotate_clockwise, 0, 22, 5, EV_full_rotate, 0, 12, EV_obstacle_front,
    0, 15, EV_obstacle_left, 0, 31, EV_obstacle_right, 0, 47, EV_path_clear, 0, 3,
    5, EV_obstacle_front, 0, 15, EV_obstacle_left, 0, 31, EV_obstacle_right, 0, 48,
    EV_path_clear, 0, 3, EV_rotate_clockwise, 0, 22, 5, EV_move_forward, 0, 9, EV_obstacle_front,
    0, 19, EV_obstacle_left, 0, 35, EV_obstacle_right, 0, 51, EV_path_clear, 0, 5,
    5, EV_full_rotate, 0, 12, EV_obstacle_front, 0, 18, EV_obstacle_left, 0, 34, EV_obstacle_right,
    0, 50, EV_path_clear, 0, 4, 5, EV_obstacle_front, 0, 18, EV_obstacle_left, 0,
    34, EV_obstacle_right, 0, 51, EV_path_clear, 0, 4, EV_rotate_clockwise, 0, 22,
    5, EV_full_rotate, 0, 12, EV_obstacle_front, 0, 20, EV_obstacle_left, 0, 37, EV_obstacle_right,
    0, 52, EV_path_clear, 0, 7, 5, EV_obstacle_front, 0, 20, EV_obstacle_left, 0,
    37, EV_obstacle_right, 0, 53, EV_path_clear, 0, 7, EV_rotate_clockwise, 0, 22,
    5, EV_obstacle_front, 0, 24, EV_obstacle_left, 0, 40, EV_obstacle_right, 0, 56,
    EV_path_clear, 0, 8, EV_random_walk, 0, 17, 5, EV_full_rotate, 0, 12, EV_obstacle_front,
    0, 23, EV_obstacle_left, 0, 39, EV_obstacle_right, 0, 55, EV_path_clear, 0, 8,
    5, EV_obstacle_front, 0, 23, EV_obstacle_left, 0, 39, EV_obstacle_right, 0, 56,
    EV_path_clear, 0, 8, EV_rotate_clockwise, 0, 22, 5, EV_obstacle_front, 0, 11,
    EV_obstacle_left, 0, 27, EV_obstacle_right, 0, 43, EV_path_clear, 0, 0, EV_random_walk,
    0, 33, 5, EV_full_rotate, 0, 28, EV_obstacle_front, 0, 10, EV_obstacle_left, 0,
    26, EV_obstacle_right, 0, 42, EV_path_clear, 0, 0, 5, EV_obstacle_front, 0, 10,
    EV_obstacle_left, 0, 27, EV_obstacle_right, 0, 42, EV_path_clear, 0, 0, EV_rotate_counterclockwise,
    0, 36, 5, EV_obstacle_front, 0, 14, EV_obstacle_left, 0, 30, EV_obstacle_right,
    0, 46, EV_path_clear, 0, 2, EV_random_walk, 0, 33, 5, EV_full_rotate, 0, 28, EV_obstacle_front,
    0, 13, EV_obstacle_left, 0, 29, EV_obstacle_right, 0, 45, EV_path_clear, 0, 2,
    5, EV_obstacle_front, 0, 13, EV_obstacle_left, 0, 30, EV_obstacle_right, 0, 45,
    EV_path_clear, 0, 2, EV_rotate_counterclockwise, 0, 36, 5, EV_full_rotate, 0,
    28, EV_obstacle_front, 0, 15, EV_obstacle_left, 0, 31, EV_obstacle_right, 0, 47,
    EV_path_clear, 0, 3, 5, EV_obstacle_front, 0, 15, EV_obstacle_left, 0, 32, EV_obstacle_right,
    0, 47, EV_path_clear, 0, 3, EV_rotate_counterclockwise, 0, 36, 5, EV_move_forward,
    0, 25, EV_obstacle_front, 0, 19, EV_obstacle_left, 0, 35, EV_obstacle_right, 0,
    51, EV_path_clear, 0, 5, 5, EV_full_rotate, 0, 28, EV_obstacle_front, 0, 18, EV_obstacle_left,
    0, 34, EV_obstacle_right, 0, 50, EV_path_clear, 0, 4, 5, EV_obstacle_front, 0,
    18, EV_obstacle_left, 0, 35, EV_obstacle_right, 0, 50, EV_path_clear, 0, 4, EV_rotate_counterclockwise,
    0, 36, 5, EV_obstacle_front, 0, 21, EV_obstacle_left, 0, 38, EV_obstacle_right,
    0, 53, EV_path_clear, 0, 7, EV_random_walk, 0, 33, 5, EV_full_rotate, 0, 28, EV_obstacle_front,
    0, 20, EV_obstacle_left, 0, 37, EV_obstacle_right, 0, 52, EV_path_clear, 0, 7,
    5, EV_obstacle_front, 0, 20, EV_obstacle_left, 0, 38, EV_obstacle_right, 0, 52,
    EV_path_clear, 0, 7, EV_rotate_counterclockwise, 0, 36, 5, EV_full_rotate, 0,
    28, EV_obstacle_front, 0, 23, EV_obstacle_left, 0, 39, EV_obstacle_right, 0, 55,
    EV_path_clear, 0, 8, 5, EV_obstacle_front, 0, 23, EV_obstacle_left, 0, 40, EV_obstacle_right,
    0, 55, EV_path_clear, 0, 8, EV_rotate_counterclockwise, 0, 36, 5, EV_obstacle_front,
    0, 11, EV_obstacle_left, 0, 27, EV_obstacle_right, 0, 43, EV_path_clear, 0, 0,
    EV_random_walk, 0, 49, 5, EV_full_rotate, 0, 44, EV_obstacle_front, 0, 10, EV_obstacle_left,
    0, 26, EV_obstacle_right, 0, 42, EV_path_clear, 0, 0, 5, EV_obstacle_front, 0,
    10, EV_obstacle_left, 0, 26, EV_obstacle_right, 0, 43, EV_path_clear, 0, 0, EV_rotate_clockwise,
    0, 54, 5, EV_obstacle_front, 0, 14, EV_obstacle_left, 0, 30, EV_obstacle_right,
    0, 46, EV_path_clear, 0, 2, EV_random_walk, 0, 49, 5, EV_full_rotate, 0, 44, EV_obstacle_front,
    0, 13, EV_obstacle_left, 0, 29, EV_obstacle_right, 0, 45, EV_path_clear, 0, 2,
    5, EV_obstacle_front, 0, 13, EV_obstacle_left, 0, 29, EV_obstacle_right, 0, 46,
    EV_path_clear, 0, 2, EV_rotate_clockwise, 0, 54, 5, EV_full_rotate, 0, 44, EV_obstacle_front,
    0, 15, EV_obstacle_left, 0, 31, EV_obstacle_right, 0, 47, EV_path_clear, 0, 3,
    5, EV_obstacle_front, 0, 15, EV_obstacle_left, 0, 31, EV_obstacle_right, 0, 48,
    EV_path_clear, 0, 3, EV_rotate_clockwise, 0, 54, 5, EV_move_forward, 0, 41, EV_obstacle_front,
    0, 19, EV_obstacle_left, 0, 35, EV_obstacle_right, 0, 51, EV_path_clear, 0, 5,
    5, EV_full_rotate, 0, 44, EV_obstacle_front, 0, 18, EV_obstacle_left, 0, 34, EV_obstacle_right,
    0, 50, EV_path_clear, 0, 4, 5, EV_obstacle_front, 0, 18, EV_obstacle_left, 0,
    34, EV_obstacle_right, 0, 51, EV_path_clear, 0, 4, EV_rotate_clockwise, 0, 54,
    5, EV_full_rotate, 0, 44, EV_obstacle_front, 0, 20, EV_obstacle_left, 0, 37, EV_obstacle_right,
    0, 52, EV_path_clear, 0, 7, 5, EV_obstacle_front, 0, 20, EV_obstacle_left, 0,
    37, EV_obstacle_right, 0, 53, EV_path_clear, 0, 7, EV_rotate_clockwise, 0, 54,
    5, EV_obstacle_front, 0, 24, EV_obstacle_left, 0, 40, EV_obstacle_right, 0, 56,
    EV_path_clear, 0, 8, EV_random_walk, 0, 49, 5, EV_full_rotate, 0, 44, EV_obstacle_front,
    0, 23, EV_obstacle_left, 0, 39, EV_obstacle_right, 0, 55, EV_path_clear, 0, 8,
    5, EV_obstacle_front, 0, 23, EV_obstacle_left, 0, 39, EV_obstacle_right, 0, 56,
    EV_path_clear, 0, 8, EV_rotate_clockwise, 0, 54]}
