{num_events: 9, num_supervisors: 1, events: [EV_full_rotate, EV_move_forward, EV_obstacle_front,
    EV_obstacle_left, EV_obstacle_right, EV_path_clear, EV_random_walk, EV_rotate_clockwise,
    EV_rotate_counterclockwise], ev_controllable: [1, 1, 0, 0, 0, 0, 1, 1, 1], sup_events: [
    [1, 1, 1, 1, 1, 1, 1, 1, 1]], sup_init_state: [2], sup_current_state: [2], sup_data_pos: [
    0], sup_data: [5, EV_move_forward, 0, 3, EV_obstacle_front, 0, 9, EV_obstacle_left,
    0, 18, EV_obstacle_right, 0, 27, EV_path_clear, 0, 0, 5, EV_move_forward, 0, 2,
    EV_obstacle_front, 0, 8, EV_obstacle_left, 0, 17, EV_obstacle_right, 0, 26, EV_path_clear,
    0, 1, 6, EV_move_forward, 0, 1, EV_obstacle_front, 0, 12, EV_obstacle_left, 0,
    21, EV_obstacle_right, 0, 30, EV_path_clear, 0, 2, EV_random_walk, 0, 0, 6, EV_move_forward,
    0, 0, EV_obstacle_front, 0, 11, EV_obstacle_left, 0, 20, EV_obstacle_right, 0,
    29, EV_path_clear, 0, 3, EV_random_walk, 0, 1, 5, EV_obstacle_front, 0, 13, EV_obstacle_left,
    0, 22, EV_obstacle_right, 0, 31, EV_path_clear, 0, 4, EV_rotate_counterclockwise,
    0, 2, 5, EV_obstacle_front, 0, 14, EV_obstacle_left, 0, 23, EV_obstacle_right,
    0, 32, EV_path_clear, 0, 5, EV_rotate_clockwise, 0, 2, 5, EV_full_rotate, 0, 2,
    EV_obstacle_front, 0, 15, EV_obstacle_left, 0, 24, EV_obstacle_right, 0, 33, EV_path_clear,
    0, 6, 5, EV_move_forward, 0, 11, EV_obstacle_front, 0, 9, EV_obstacle_left, 0,
    18, EV_obstacle_right, 0, 27, EV_path_clear, 0, 0, 5, EV_move_forward, 0, 10,
    EV_obstacle_front, 0, 8, EV_obstacle_left, 0, 17, EV_obstacle_right, 0, 26, EV_path_clear,
    0, 1, 4, EV_obstacle_front, 0, 9, EV_obstacle_left, 0, 18, EV_obstacle_right,
    0, 27, EV_path_clear, 0, 0, 6, EV_move_forward, 0, 8, EV_obstacle_front, 0, 12,
    EV_obstacle_left, 0, 21, EV_obstacle_right, 0, 30, EV_path_clear, 0, 2, EV_random_walk,
    0, 7, 6, EV_move_forward, 0, 7, EV_obstacle_front, 0, 11, EV_obstacle_left, 0,
    20, EV_obstacle_right, 0, 29, EV_path_clear, 0, 3, EV_random_walk, 0, 8, 6, EV_full_rotate,
    0, 15, EV_obstacle_front, 0, 12, EV_obstacle_left, 0, 21, EV_obstacle_right, 0,
    30, EV_path_clear, 0, 2, EV_random_walk, 0, 9, 5, EV_obstacle_front, 0, 13, EV_obstacle_left,
    0, 22, EV_obstacle_right, 0, 31, EV_path_clear, 0, 4, EV_rotate_counterclockwise,
    0, 10, 5, EV_obstacle_front, 0, 14, EV_obstacle_left, 0, 23, EV_obstacle_right,
    0, 32, EV_path_clear, 0, 5, EV_rotate_clockwise, 0, 10, 5, EV_full_rotate, 0,
    10, EV_obstacle_front, 0, 15, EV_obstacle_left, 0, 24, EV_obstacle_right, 0, 33,
    EV_path_clear, 0, 6, 5, EV_move_forward, 0, 20, EV_obstacle_front, 0, 9, EV_obstacle_left,
    0, 18, EV_obstacle_right, 0, 27, EV_path_clear, 0, 0, 5, EV_move_forward, 0, 19,
    EV_obstacle_front, 0, 8, EV_obstacle_left, 0, 17, EV_obstacle_right, 0, 26, EV_path_clear,
    0, 1, 4, EV_obstacle_front, 0, 9, EV_obstacle_left, 0, 18, EV_obstacle_right,
    0, 27, EV_path_clear, 0, 0, 6, EV_move_forward, 0, 17, EV_obstacle_front, 0, 12,
    EV_obstacle_left, 0, 21, EV_obstacle_right, 0, 30, EV_path_clear, 0, 2, EV_random_walk,
    0, 16, 6, EV_move_forward, 0, 16, EV_obstacle_front, 0, 11, EV_obstacle_left,
    0, 20, EV_obstacle_right, 0, 29, EV_path_clear, 0, 3, EV_random_walk, 0, 17, 6,
    EV_obstacle_front, 0, 12, EV_obstacle_left, 0, 21, EV_obstacle_right, 0, 30, EV_path_clear,
    0, 2, EV_random_walk, 0, 18, EV_rotate_clockwise, 0, 23, 5, EV_obstacle_front,
    0, 13, EV_obstacle_left, 0, 22, EV_obstacle_right, 0, 31, EV_path_clear, 0, 4,
    EV_rotate_counterclockwise, 0, 19, 5, EV_obstacle_front, 0, 14, EV_obstacle_left,
    0, 23, EV_obstacle_right, 0, 32, EV_path_clear, 0, 5, EV_rotate_clockwise, 0,
    19, 5, EV_full_rotate, 0, 19, EV_obstacle_front, 0, 15, EV_obstacle_left, 0, 24,
    EV_obstacle_right, 0, 33, EV_path_clear, 0, 6, 5, EV_move_forward, 0, 29, EV_obstacle_front,
    0, 9, EV_obstacle_left, 0, 18, EV_obstacle_right, 0, 27, EV_path_clear, 0, 0,
    5, EV_move_forward, 0, 28, EV_obstacle_front, 0, 8, EV_obstacle_left, 0, 17, EV_obstacle_right,
    0, 26, EV_path_clear, 0, 1, 4, EV_obstacle_front, 0, 9, EV_obstacle_left, 0, 18,
    EV_obstacle_right, 0, 27, EV_path_clear, 0, 0, 6, EV_move_forward, 0, 26, EV_obstacle_front,
    0, 12, EV_obstacle_left, 0, 21, EV_obstacle_right, 0, 30, EV_path_clear, 0, 2,
    EV_random_walk, 0, 25, 6, EV_move_forward, 0, 25, EV_obstacle_front, 0, 11, EV_obstacle_left,
    0, 20, EV_obstacle_right, 0, 29, EV_path_clear, 0, 3, EV_random_walk, 0, 26, 6,
    EV_obstacle_front, 0, 12, EV_obstacle_left, 0, 21, EV_obstacle_right, 0, 30, EV_path_clear,
    0, 2, EV_random_walk, 0, 27, EV_rotate_counterclockwise, 0, 31, 5, EV_obstacle_front,
    0, 13, EV_obstacle_left, 0, 22, EV_obstacle_right, 0, 31, EV_path_clear, 0, 4,
    EV_rotate_counterclockwise, 0, 28, 5, EV_obstacle_front, 0, 14, EV_obstacle_left,
    0, 23, EV_obstacle_right, 0, 32, EV_path_clear, 0, 5, EV_rotate_clockwise, 0,
    28, 5, EV_full_rotate, 0, 28, EV_obstacle_front, 0, 15, EV_obstacle_left, 0, 24,
    EV_obstacle_right, 0, 33, EV_path_clear, 0, 6]}
