
num_events: 16
num_supervisors: 3
events: [ EV_moveStop, EV_getNotR, EV_sendG, EV_moveEnded, EV_getNotB, EV_sendNothing, EV_getR, EV_sendB, EV_turnCW, EV_getNotG, EV_moveFW, EV_turnCCW, EV_press, EV_getG, EV_sendR, EV_getB ]
ev_controllable: [ 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0 ]
sup_events: [ [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0], [1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0], [1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1] ]
sup_init_state: [ 2, 1, 0 ]
sup_current_state: [ 2, 1, 0 ]
sup_data_pos: [ 0, 44, 109 ]
sup_data: [ 2, EV_press, 0, 0, EV_sendB, 0, 7, 1, EV_press, 0, 6, 1, EV_press, 0, 3, 2, EV_press, 0, 3, EV_sendR, 0, 1, 2, EV_press, 0, 4, EV_sendNothing, 0, 2, 1, EV_press, 0, 0, 2, EV_press, 0, 6, EV_sendG, 0, 5, 1, EV_press, 0, 4, 1, EV_sendG, 0, 6, 4, EV_turnCW, 0, 4, EV_turnCCW, 0, 4, EV_sendR, 0, 0, EV_moveFW, 0, 4, 3, EV_sendG, 0, 7, EV_moveEnded, 0, 0, EV_moveStop, 0, 0, 3, EV_moveStop, 0, 5, EV_moveEnded, 0, 5, EV_sendNothing, 0, 4, 3, EV_sendR, 0, 2, EV_moveEnded, 0, 1, EV_moveStop, 0, 1, 1, EV_sendNothing, 0, 1, 1, EV_sendB, 0, 5, 3, EV_moveStop, 0, 6, EV_moveEnded, 0, 6, EV_sendB, 0, 3, 3, EV_getR, 0, 4, EV_getG, 0, 6, EV_getB, 0, 9, 6, EV_getG, 0, 5, EV_turnCCW, 0, 12, EV_moveFW, 0, 12, EV_getNotB, 0, 4, EV_getNotR, 0, 9, EV_turnCW, 0, 12, 4, EV_getB, 0, 8, EV_moveEnded, 0, 13, EV_getNotG, 0, 7, EV_getNotR, 0, 3, 5, EV_moveStop, 0, 6, EV_getR, 0, 2, EV_getNotG, 0, 10, EV_moveEnded, 0, 6, EV_getB, 0, 15, 3, EV_getG, 0, 13, EV_getNotR, 0, 0, EV_getB, 0, 1, 6, EV_moveFW, 0, 8, EV_getNotB, 0, 13, EV_getNotR, 0, 11, EV_turnCW, 0, 8, EV_getNotG, 0, 1, EV_turnCCW, 0, 8, 3, EV_getB, 0, 11, EV_getR, 0, 13, EV_getNotG, 0, 0, 5, EV_getG, 0, 2, EV_getNotR, 0, 10, EV_moveStop, 0, 4, EV_getB, 0, 12, EV_moveEnded, 0, 4, 4, EV_getNotB, 0, 2, EV_getNotR, 0, 15, EV_moveEnded, 0, 5, EV_getNotG, 0, 12, 3, EV_getR, 0, 1, EV_getG, 0, 11, EV_getNotB, 0, 0, 5, EV_moveEnded, 0, 0, EV_getR, 0, 7, EV_getB, 0, 14, EV_getG, 0, 3, EV_moveStop, 0, 0, 6, EV_getNotB, 0, 6, EV_moveFW, 0, 15, EV_getNotG, 0, 9, EV_turnCW, 0, 15, EV_getR, 0, 5, EV_turnCCW, 0, 15, 4, EV_getNotR, 0, 14, EV_getNotB, 0, 7, EV_getG, 0, 8, EV_moveEnded, 0, 1, 6, EV_getB, 0, 5, EV_turnCCW, 0, 2, EV_getNotR, 0, 6, EV_moveFW, 0, 2, EV_turnCW, 0, 2, EV_getNotG, 0, 4, 5, EV_getNotB, 0, 10, EV_moveStop, 0, 9, EV_getG, 0, 15, EV_moveEnded, 0, 9, EV_getR, 0, 12, 4, EV_getNotB, 0, 3, EV_getR, 0, 8, EV_getNotG, 0, 14, EV_moveEnded, 0, 11 ]


action_map:
  move_forward: EV_moveFW
  turn_clockwise: EV_turnCW
  turn_counter_clockwise: EV_turnCCW
  press: EV_press
  stop: EV_moveStop
  send_green: EV_sendG
  send_red: EV_sendR
  send_blue: EV_sendB
  send_nothing: EV_sendNothing

sensor_map:
  get_signal_R: EV_getR
  get_signal_not_R: EV_getNotR
  get_signal_B: EV_getB
  get_signal_not_B: EV_getNotB
  get_signal_G: EV_getG
  get_signal_not_G: EV_getNotG