{num_events: 14, num_supervisors: 1, events: [EV_full_rotate, EV_marker_close, EV_marker_lost,
    EV_marker_seen, EV_move_forward, EV_move_to_marker, EV_obstacle_front, EV_obstacle_left,
    EV_obstacle_right, EV_path_clear, EV_random_walk, EV_rotate_clockwise, EV_rotate_counterclockwise,
    EV_stop], ev_controllable: [1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1], sup_events: [
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], sup_init_state: [0], sup_current_state: [
    0], sup_data_pos: [0], sup_data: [9, EV_full_rotate, 0, 7, EV_marker_close, 0,
    1, EV_marker_lost, 0, 0, EV_marker_seen, 0, 2, EV_move_forward, 0, 6, EV_obstacle_front,
    0, 3, EV_obstacle_left, 0, 4, EV_obstacle_right, 0, 5, EV_path_clear, 0, 0, 8,
    EV_marker_close, 0, 1, EV_marker_lost, 0, 1, EV_marker_seen, 0, 1, EV_obstacle_front,
    0, 1, EV_obstacle_left, 0, 1, EV_obstacle_right, 0, 1, EV_path_clear, 0, 1, EV_stop,
    0, 1, 8, EV_marker_close, 0, 1, EV_marker_lost, 0, 7, EV_marker_seen, 0, 2, EV_move_to_marker,
    0, 11, EV_obstacle_front, 0, 3, EV_obstacle_left, 0, 2, EV_obstacle_right, 0,
    2, EV_path_clear, 0, 2, 8, EV_full_rotate, 0, 7, EV_marker_close, 0, 1, EV_marker_lost,
    0, 3, EV_marker_seen, 0, 2, EV_obstacle_front, 0, 3, EV_obstacle_left, 0, 4, EV_obstacle_right,
    0, 5, EV_path_clear, 0, 0, 8, EV_marker_close, 0, 1, EV_marker_lost, 0, 4, EV_marker_seen,
    0, 2, EV_obstacle_front, 0, 3, EV_obstacle_left, 0, 4, EV_obstacle_right, 0, 5,
    EV_path_clear, 0, 0, EV_rotate_clockwise, 0, 8, 8, EV_marker_close, 0, 1, EV_marker_lost,
    0, 5, EV_marker_seen, 0, 2, EV_obstacle_front, 0, 3, EV_obstacle_left, 0, 4, EV_obstacle_right,
    0, 5, EV_path_clear, 0, 0, EV_rotate_counterclockwise, 0, 9, 8, EV_marker_close,
    0, 1, EV_marker_lost, 0, 6, EV_marker_seen, 0, 2, EV_move_forward, 0, 0, EV_obstacle_front,
    0, 3, EV_obstacle_left, 0, 4, EV_obstacle_right, 0, 5, EV_path_clear, 0, 0, 8,
    EV_full_rotate, 0, 10, EV_marker_close, 0, 1, EV_marker_lost, 0, 7, EV_marker_seen,
    0, 2, EV_obstacle_front, 0, 3, EV_obstacle_left, 0, 4, EV_obstacle_right, 0, 5,
    EV_path_clear, 0, 0, 8, EV_marker_close, 0, 1, EV_marker_lost, 0, 8, EV_marker_seen,
    0, 2, EV_obstacle_front, 0, 3, EV_obstacle_left, 0, 4, EV_obstacle_right, 0, 5,
    EV_path_clear, 0, 0, EV_rotate_clockwise, 0, 0, 8, EV_marker_close, 0, 1, EV_marker_lost,
    0, 9, EV_marker_seen, 0, 2, EV_obstacle_front, 0, 3, EV_obstacle_left, 0, 4, EV_obstacle_right,
    0, 5, EV_path_clear, 0, 0, EV_rotate_counterclockwise, 0, 0, 8, EV_marker_close,
    0, 1, EV_marker_lost, 0, 10, EV_marker_seen, 0, 2, EV_move_forward, 0, 7, EV_obstacle_front,
    0, 3, EV_obstacle_left, 0, 4, EV_obstacle_right, 0, 5, EV_path_clear, 0, 10, 8,
    EV_marker_close, 0, 1, EV_marker_lost, 0, 7, EV_marker_seen, 0, 2, EV_move_to_marker,
    0, 2, EV_obstacle_front, 0, 3, EV_obstacle_left, 0, 11, EV_obstacle_right, 0,
    11, EV_path_clear, 0, 2]}
